local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pv', vim.cmd.Ex)
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<leader>ps', function()
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
